# Generated by Django 4.2.7 on 2023-11-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_heading_desc_heading_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='heading',
        ),
    ]
